set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
if(NOT DEFINED ENV{VICOS_SDK})
  message(FATAL_ERROR "VICOS_SDK must name the SDK root")
endif()
set(VICOS_SDK "$ENV{VICOS_SDK}")
set(CMAKE_SYSROOT "${VICOS_SDK}/sysroot")
set(_bin "${VICOS_SDK}/prebuilt/bin")
set(CMAKE_C_COMPILER "${_bin}/arm-oe-linux-gnueabi-clang")
set(CMAKE_CXX_COMPILER "${_bin}/arm-oe-linux-gnueabi-clang++")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
set(CMAKE_C_COMPILER_TARGET arm-oe-linux-gnueabi)
set(CMAKE_CXX_COMPILER_TARGET arm-oe-linux-gnueabi)
set(CMAKE_AR "${_bin}/arm-oe-linux-gnueabi-ar")
set(CMAKE_RANLIB "${_bin}/arm-oe-linux-gnueabi-ranlib")
set(CMAKE_STRIP "${_bin}/arm-oe-linux-gnueabi-strip")
set(_abi "-march=armv7-a -mfloat-abi=softfp -mfpu=neon-vfpv4")
set(CMAKE_C_FLAGS_INIT "${_abi}")
set(CMAKE_CXX_FLAGS_INIT "${_abi} -stdlib=libc++ -Qunused-arguments")
set(CMAKE_ASM_FLAGS_INIT "${_abi}")
set(_link "-B${_bin} -Wl,-rpath-link,${CMAKE_SYSROOT}/lib -Wl,-rpath-link,${CMAKE_SYSROOT}/usr/lib")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_link}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_link}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_link}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
